// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DemoGen = require("./Demo.gen");

function lighten(prim, prim$1) {
  return DemoGen.lighten(prim, prim$1);
}

console.log("Hello, World!", DemoGen.lighten(0.5, "#CCCD64"));

exports.lighten = lighten;
/*  Not a pure module */
